const languageAvailable = [
  {
    name: 'Arabic',
    nativeName: 'العربية',
    langCode: 'ar',
    flag: 'ar.png',
  },
  {
    name: 'Bulgarian',
    nativeName: 'български език',
    langCode: 'bg',
    flag: 'bg.png',
  },
  {
    name: 'Chinese (Simplified)',
    nativeName: '中文 (Zhōngwén), 汉语, 漢語',
    langCode: 'zh-CN',
    flag: 'zh-CN.png',
  },
  {
    name: 'Chinese (Traditional)',
    nativeName: '中文 (Zhōngwén), 汉语, 漢語',
    langCode: 'zh-TW',
    flag: 'zh-TW.png',
  },
  {
    name: 'Croatian',
    nativeName: 'hrvatski',
    langCode: 'hr',
    flag: 'hr.png',
  },
  {
    name: 'Czech',
    nativeName: 'česky, čeština',
    langCode: 'cs',
    flag: 'cs.png',
  },
  {
    name: 'Danish',
    nativeName: 'dansk',
    langCode: 'da',
    flag: 'da.png',
  },
  {
    name: 'Dutch',
    nativeName: 'Nederlands, Vlaams',
    langCode: 'nl',
    flag: 'nl.png',
  },
  {
    name: 'English',
    nativeName: 'English',
    langCode: 'en',
    flag: 'en.png',
  },
  {
    name: 'Finnish',
    nativeName: 'suomi, suomen kieli',
    langCode: 'fi',
    flag: 'fi.png',
  },
  {
    name: 'French',
    nativeName: 'français, langue française',
    langCode: 'fr',
    flag: 'fr.png',
  },
  {
    name: 'German',
    nativeName: 'Deutsch',
    langCode: 'de',
    flag: 'de.png',
  },
  {
    name: 'Greek, Modern',
    nativeName: 'Ελληνικά',
    langCode: 'el',
    flag: 'el.png',
  },
  {
    name: 'Italian',
    nativeName: 'Italiano',
    langCode: 'it',
    flag: 'it.png',
  },
  {
    name: 'Japanese',
    nativeName: '日本語 (にほんご／にっぽんご)',
    langCode: 'jp',
    flag: 'jp.png',
  },
  {
    name: 'Korean',
    nativeName: '한국어 (韓國語), 조선말 (朝鮮語)',
    langCode: 'kr',
    flag: 'kr.png',
  },
  {
    name: 'Lithuanian',
    nativeName: 'lietuvių kalba',
    langCode: 'lt',
    flag: 'lt.png',
  },
  {
    name: 'Norwegian',
    nativeName: 'Norsk',
    langCode: 'no',
    flag: 'no.png',
  },
  {
    name: 'Polish',
    nativeName: 'polski',
    langCode: 'pl',
    flag: 'pl.png',
  },
  {
    name: 'Portuguese',
    nativeName: 'Português',
    langCode: 'pt',
    flag: 'pt.png',
  },
  {
    name: 'Romanian, Moldavian, Moldovan',
    nativeName: 'română',
    langCode: 'ro',
    flag: 'ro.png',
  },
  {
    name: 'Russian',
    nativeName: 'русский язык',
    langCode: 'ru',
    flag: 'ru.png',
  },
  {
    name: 'Serbian',
    nativeName: 'српски језик',
    langCode: 'sr',
    flag: 'sr.png',
  },
  {
    name: 'Slovak',
    nativeName: 'slovenčina',
    langCode: 'sk',
    flag: 'sk.png',
  },
  {
    name: 'Slovene',
    nativeName: 'slovenščina',
    langCode: 'sl',
    flag: 'sl.png',
  },
  {
    name: 'Spanish; Castilian',
    nativeName: 'español, castellano',
    langCode: 'es',
    flag: 'es.png',
  },
  {
    name: 'Swedish',
    nativeName: 'svenska',
    langCode: 'sv',
    flag: 'sv.png',
  },
  {
    name: 'Turkish',
    nativeName: 'Türkçe',
    langCode: 'tr',
    flag: 'tr.png',
  },
  {
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    langCode: 'vi',
    flag: 'vi.png',
  },
];
export default languageAvailable;
